version: '3.1'
services:
  puppet:
    image: uscdev/puppet
    ports:
      - 8140:8140
    networks:
      web-bus:
#   volumes:
#     - /etc/puppetlabs/puppet/ssl
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  web-bus:
    external:
      name: web-bus

